version: "3.8"

services:
  prom1:
    image: prom/prometheus
    user: root
    volumes:
      - ./prom1.yml:/etc/prometheus/prometheus.yml
      - ./data1:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-admin-api
      - --storage.tsdb.max-block-duration=5m 
      - --storage.tsdb.min-block-duration=5m
      - --storage.tsdb.retention.time=20m
    expose:
     - 9090
  prom2:
    image: prom/prometheus
    user: root
    volumes:
      - ./prom2.yml:/etc/prometheus/prometheus.yml
      - ./data2:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-admin-api
      - --storage.tsdb.max-block-duration=5m 
      - --storage.tsdb.min-block-duration=5m
      - --storage.tsdb.retention.time=20m
    expose:
     - 9090
  prom3:
    image: prom/prometheus
    user: root
    volumes:
      - ./prom3.yml:/etc/prometheus/prometheus.yml
      - ./data3:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-admin-api
      - --storage.tsdb.max-block-duration=5m 
      - --storage.tsdb.min-block-duration=5m
      - --storage.tsdb.retention.time=20m
    expose:
     - 9090
  prom4:
    image: prom/prometheus
    user: root
    volumes:
      - ./prom4.yml:/etc/prometheus/prometheus.yml
      - ./data4:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-admin-api
      - --storage.tsdb.max-block-duration=5m 
      - --storage.tsdb.min-block-duration=5m
      - --storage.tsdb.retention.time=20m
    expose:
     - 9090
  query:
    image: thanos
    command:
      - query
      - --store=receive1:10901
      - --store=receive2:10901
      - --store=receive3:10901
      - --store=store:10901
      - --query.replica-label=replica
      - --query.replica-label=receive_replica
    ports:
      - 10902:10902
  minio:
    image: minio/minio:RELEASE.2021-09-03T03-56-13Z
    volumes:
      - ./minio:/data
    command:
      - server
      - /data
      - --console-address
      - :9001
    environment:
      MINIO_ACCESS_KEY: admin123
      MINIO_SECRET_KEY: admin123
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  store:
    image: thanos
    volumes:
      - ./bucket.yml:/bucket.yml
    command:
      - store
      - --objstore.config-file=/bucket.yml
    ports:
      - 10903:10902
    expose:
      - 10901
    depends_on:
      - minio
    restart: unless-stopped
  receive1:
    image: thanos
    volumes:
      - ./hashring.json:/hashring.json
      - ./receive1-data:/data
      - ./bucket.yml:/bucket.yml
    command:
      - receive
      - --tsdb.path=/data
      - --receive.replication-factor=2
      - "--label=receive_replica=\"0\""
      - --receive.local-endpoint=receive1:10901
      - --receive.hashrings-file=/hashring.json
      - --objstore.config-file=/bucket.yml
    restart: unless-stopped
  receive2:
    image: thanos
    volumes:
      - ./hashring.json:/hashring.json
      - ./receive2-data:/data
      - ./bucket.yml:/bucket.yml
    command:
      - receive
      - --tsdb.path=/data
      - --receive.replication-factor=2
      - "--label=receive_replica=\"1\""
      - --receive.local-endpoint=receive2:10901
      - --receive.hashrings-file=/hashring.json
      - --objstore.config-file=/bucket.yml
    restart: unless-stopped
  receive3:
    image: thanos
    volumes:
      - ./hashring.json:/hashring.json
      - ./receive3-data:/data
      - ./bucket.yml:/bucket.yml
    command:
      - receive
      - --tsdb.path=/data
      - --receive.replication-factor=2
      - "--label=receive_replica=\"2\""
      - --receive.local-endpoint=receive3:10901
      - --receive.hashrings-file=/hashring.json
      - --objstore.config-file=/bucket.yml
    restart: unless-stopped
  compactor:
    image: thanos
    volumes: 
      - ./thanos-compact:/thanos-compact
      - ./bucket.yml:/bucket.yml
    command:
      - compact
      - --objstore.config-file=/bucket.yml
      - --data-dir=thanos-compact
      - --wait
    ports:
      - 10999:10902
    restart: unless-stopped